### ISSUE TITLE
Unlocking password safe fails when compiling with recent gcc versions

### ISSUE THREAD

**Issue by MaVo159** [Nitrokey/nitrokey-pro-firmware#9] opened 2016-07-30 12:21 UTC
Sending the command that enables the pws returns a respose with status: CMD_STATUS_AES_DEC_FAILED

**Comment by szszszsz** [comment] 2016-10-27 10:05
Hi!
Could you post the compiler version you have tested?
I have tested this issue on current master with `gcc 5.4` and it is not occuring. I guess the cause was misused `memcpy` (https://github.com/Nitrokey/nitrokey-pro-firmware/commit/4daceed22d716a3c9433413f3b9b7ca83828490c).

**Comment by MaVo159** [comment] 2016-10-27 11:03
I suspected the same because the first wrong memcpy was exactly at this place. Didn't have time to confirm. I don't remember my gcc version. I suspect it was a bit newer than 5.4.

**Comment by szszszsz** [comment] 2016-10-27 11:04
OK, thank you. I will run tests thoroughly before closing.

**Comment by szszszsz** [comment] 2016-11-12 17:19
Issue is not occurring on latest commit. It might be also caused by not regenerating AES keys after factory reset (detailed log below).
[AES_DEC_FAILED_example.txt](https://github.com/Nitrokey/nitrokey-pro-firmware/files/587350/AES_DEC_FAILED_example.txt)

**Closed by szszszsz** 2016-11-12 17:19 UTC
